name: React CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    statergy:
        matrix:
            node-version: [16x]
    steps:
       - uses: actions/checkout@v1
       - run: npm install
       - run: npm run build
       - run: npm test
