name: React CI

on:
  push:
    branches:
         - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    statergy:
        matrix:
            node-version: [15x]
    steps:
       - uses: actions/checkout@v1
       - run: npm install
       - run: npm run build
       - run: npm test
