name: React CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v1
         with:
            node-version: 16
       - run: npm install
       - run: npm run build
       - run: npm test
